### ISSUE TITLE
Library install

### ISSUE THREAD

**Issue by joriws** [dknowles2/pytboss#83]
Sorry for basic question - but how do I install the library? Would you add relevant information to readme.md, please. I try to use code from "Usage" part of readme.md.

`
# python3 -V
Python 3.7.3
# cat ble_scan_20220925_pbc_active.txt
4B:6C:79:B9:08:53 PBC-09ED444
`

My first guess install chain is not working. Requirements.txt has been manually installed.
`
root@raspberrypi3bp:~/pitboss/api-tests# pip3 install git+https://github.com/dknowles2/pytboss
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/dknowles2/pytboss
  Cloning https://github.com/dknowles2/pytboss to /tmp/pip-req-build-sy923x8s
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-sy923x8s/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-sy923x8s/
`

or in cloned repo-dir the example code you have on readme.md..

`
root@raspberrypi3bp:~/pitboss/pytboss/pytboss# python3 jorge_test.py
Traceback (most recent call last):
  File "jorge_test.py", line 3, in <module>
    from pytboss import BleConnection, PitBoss
  File "/root/pitboss/pytboss/pytboss/pytboss/__init__.py", line 3, in <module>
    from .api import PitBoss  # noqa: F401
  File "/root/pitboss/pytboss/pytboss/pytboss/api.py", line 186
    match payload[:4]:
                ^
SyntaxError: invalid syntax
`

The main problem is that I've "car-01-pg" wifi/bluetooth upgrade board for pg850gw which is listed on supported grills. However on home assistant integration which is based on pytboss I get grill discovered but after adding all sensors are blank. So by using pytboss library I'd like to try to debug what could be wrong.

**Comment by joriws** [comment]
Home assistant integration is this https://github.com/dknowles2/ha-pitboss and installed via HACS.

**Comment by joriws** [comment]
I compiled Python3.11 as on ha-pitboss it was used. Now I think library works and installs via pip3 install git+https...
